---
title: "Raman analysis of laccase mutants"
author: "Leonard Blaschek"
date: "11/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(showtext)
# library(qrencoder)
library(cowplot)
library(grid)
library(gridExtra)
library(tidyverse)
library(ggrepel)
library(ggridges)
library(cowplot)
library(jsonlite)
library(slider)
library(lubridate)
library(baseline)
library(tukeygrps)

#### import Helvetica ####
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 6,
                      base_family = "Helvetica"
                      ) {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      axis.ticks = element_line(
        size = 0.125,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        size = 6,
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        size = 6,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_text(
        colour = "black",
        size = 6
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      axis.line = element_line(size = 0.2),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 6),
      legend.key.height = unit(4, "mm"),
      plot.title = element_text(
        size = 6,
        hjust = 0
      ),
      complete = TRUE
    )
}

pal_ostwald_disc <- c(
  "#275d95",
  "#e8c245",
  "#d25952"
)

pal_pedersen_disc <- c(
  "#264653",
  "#2a9d8f",
  "#e9c46a",
  "#f4a261",
  "#e76f51"
)

ggtext_size <- 6 / (14 / 5)
cm_size <- function(x) x / 2.54
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54

#### machine dependent paths ####
## office
datapath <- "/data/"

## laptop
# datapath <- "/home/leonard/Documents/Uni/"

```

## Load spectra

```{r, echo=FALSE, fig.showtext=TRUE, message=FALSE, warning=FALSE, out.width='100%'}
rmn_files <-
  list.files(
    path = paste0(datapath, "PhD/Raman/2020-11_lac_mutants/"),
    pattern = "*.txt",
    recursive = TRUE,
    full.names = TRUE
  )

read_plus <- function(flnm) {
  read_tsv(flnm,
    comment = "#",
    col_names = c("wavenumber", "intensity"),
    col_types = "cc",
    # locale = locale(decimal_mark = ",")
  ) %>%
    mutate(
      filename = basename(flnm)
    ) %>%
    separate(filename, into = c("date", "genotype", "replicate", "cell_type", "TE"), sep = "_") %>%
    select(-date) %>%
    mutate(
      wavenumber = as.numeric(str_replace(wavenumber, fixed(","), fixed("."))),
      intensity = as.numeric(str_replace(intensity, fixed(","), fixed("."))),
      TE = str_remove(TE, fixed(".txt")),
    ) %>%
    filter(wavenumber > 300 & 
             cell_type != "IFML") %>%
    pivot_wider(
      id_cols = c(genotype, replicate, cell_type, TE),
      names_from = wavenumber,
      values_from = intensity
    ) %>%
    group_by(genotype, replicate, cell_type, TE) %>%
    nest()
}

rmn_lac <- map(rmn_files, read_plus) %>%
  bind_rows() 

#### baseline correction ####
rmn_als <- function(x) {
  corrected_spectra <- baseline.als(as.matrix(x),
    lambda = 5,
    p = 0.01,
    maxit = 100
  )
  as_tibble(corrected_spectra$corrected, rownames = NA)
}

rmn_lac_corrected <- rmn_lac %>%
  mutate(corrected_data = map(data, rmn_als)) %>%
  select(-data) %>%
  unnest() %>%
  pivot_longer(-c(genotype, cell_type, replicate, TE),
    names_to = "wavenumber",
    values_to = "corrected.intensity"
  ) %>%
  drop_na() %>%
  mutate(wavenumber = as.numeric(wavenumber))

#### filtering and scaling ####

# alignment
lig_peak <- rmn_lac_corrected %>%
  unite("ID",
    genotype, cell_type, replicate, TE,
    remove = F,
    sep = "_"
  ) %>%
  filter(round(wavenumber, digits = 0) %in% c(370:390)) %>%
  group_by(genotype, replicate, cell_type, TE) %>%
  mutate(
    peak_pos = wavenumber[which.max(corrected.intensity)]
  ) %>%
  select(-wavenumber, -corrected.intensity) %>%
  unique() %>%
  group_by(genotype, cell_type) %>%
  mutate(peak_pos_ref = peak_pos[replicate == 5 & TE == 1])

rmn_lac_aligned <- rmn_lac_corrected %>%
  left_join(lig_peak) %>%
  group_by(genotype, replicate, cell_type, TE, wavenumber) %>%
  mutate(wavenumber = wavenumber + (peak_pos_ref - peak_pos))

# scaling and filtering
rmn_lac_scaled <- rmn_lac_aligned %>%
  group_by(genotype, cell_type, replicate, TE) %>%
  mutate(
    AUC = MESS::auc(wavenumber, corrected.intensity),
    scaled = corrected.intensity / AUC,
    scaled_lig = corrected.intensity / (
      (corrected.intensity[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1] / 2) + corrected.intensity[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1]
    ),
    scaled_cellu = corrected.intensity / 
      corrected.intensity[abs(wavenumber - 375) == min(abs(wavenumber - 375))][1]
  )

rmn_lac_avg <- rmn_lac_scaled %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  group_by(genotype, cell_type) %>%
  arrange(genotype, cell_type, wavenumber) %>%
  summarise(
    roll_mean = slider::slide_index_dbl(scaled, wavenumber, mean, .before = 1, .after = 1),
    roll_sd = slider::slide_index_dbl(scaled, wavenumber, sd, .before = 2, .after = 2),
    roll_scaled_cellu = slider::slide_index_dbl(scaled_cellu, wavenumber, mean, .before = 1, .after = 1),
    wavenumber = wavenumber
    )

rmn_lac_sum <- rmn_lac_scaled %>%
  group_by(genotype, cell_type, replicate, TE) %>%
  summarise(
    "unscaled_lignin" = 
      (corrected.intensity[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1] / 2) +
      corrected.intensity[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1],
    "broad_lignin" = 
      corrected.intensity[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1] +
      corrected.intensity[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1] +
      corrected.intensity[abs(wavenumber - 1656) == min(abs(wavenumber - 1656))][1] +
      corrected.intensity[abs(wavenumber - 1625) == min(abs(wavenumber - 1625))][1],
    "total_lignin" = (scaled[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1] / 2) +
      scaled[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1],
    "P_rel" = scaled_lig[abs(wavenumber - 990) == min(abs(wavenumber - 990))][1],
    "G_rel" = scaled_lig[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1],
    "G_tot" = scaled[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1],
    "GOH_rel" = scaled_lig[abs(wavenumber - 1656) == min(abs(wavenumber - 1656))][1],
    "GCHO_rel" = scaled_lig[abs(wavenumber - 1625) == min(abs(wavenumber - 1625))][1],
    "GCHO_tot" = scaled[abs(wavenumber - 1625) == min(abs(wavenumber - 1625))][1],
    "S_rel" = scaled_lig[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1],
    "S_tot" = scaled[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1],
    "cellulose" =
      scaled[abs(wavenumber - 1095) == min(abs(wavenumber - 1095))][1] +
        scaled[abs(wavenumber - 375) == min(abs(wavenumber - 375))][1] +
        scaled[abs(wavenumber - 1120) == min(abs(wavenumber - 1120))][1],
    "cellu_cryst" = scaled[abs(wavenumber - 375) == min(abs(wavenumber - 375))][1] /
      scaled[abs(wavenumber - 1095) == min(abs(wavenumber - 1095))][1],
    "lig.cellu" = total_lignin / cellulose,
    "G.cellu" = scaled_cellu[abs(wavenumber - 990) == min(abs(wavenumber - 990))][1],
    "P.cellu" = scaled_cellu[abs(wavenumber - 990) == min(abs(wavenumber - 990))][1],
    "S.G" = scaled_lig[abs(wavenumber - 1330) == min(abs(wavenumber - 1330))][1] /
      scaled_lig[abs(wavenumber - 1276) == min(abs(wavenumber - 1276))][1],
    "GOH.G" = scaled_lig[abs(wavenumber - 1656) == min(abs(wavenumber - 1656))][1] /
      scaled_lig[abs(wavenumber - 1600) == min(abs(wavenumber - 1600))][1],
    "GCHO.GOH" = scaled_lig[abs(wavenumber - 1625) == min(abs(wavenumber - 1625))][1] /
      scaled_lig[abs(wavenumber - 1656) == min(abs(wavenumber - 1656))][1],
    "O4_van_rel" = scaled_lig[abs(wavenumber - 1303) == min(abs(wavenumber - 1303))][1],
    "other_van_rel" = scaled_lig[abs(wavenumber - 785) == min(abs(wavenumber - 785))][1],
    "O4_syr_rel" = scaled_lig[abs(wavenumber - 1297) == min(abs(wavenumber - 1297))][1],
    "other_syr_rel" = scaled_lig[abs(wavenumber - 450) == min(abs(wavenumber - 450))][1],
    "Benz_rel" = O4_van_rel + other_van_rel + O4_syr_rel + other_syr_rel,
    "AUC" = mean(AUC)
  )

```

## View spectra

```{r}
rmn_lac_test <- ggplot(
  rmn_lac_scaled %>% filter(genotype == "WT" & cell_type == "MX"),
  aes(
    x = wavenumber,
    y = scaled_cellu
  )
) +
  scale_x_continuous(trans = "reverse",
                     # limits = c(1020, 980)
                     ) +
  # scale_y_continuous(limits = c(-0.001, 0.003)) +
  geom_vline(xintercept = c(1656, 1600, 1330, 1120, 1095, 990, 855, 375),
             size = 0.2) +
  # annotate("text",
  #          label = c("1660", "1600", "1330", "1120", "1095", "1001", "375"),
  #          y = 0.007,
  #          x = c(1661, 1601, 1331, 1170, 1096, 1002, 376),
  #          hjust = 0,
  #          family = "Helvetica",
  #          size = ggtext_size) +
  geom_line(aes(
    group = interaction(cell_type, replicate, TE),
    colour = cell_type
  ),
  alpha = 0.25,
  size = 0.1
  ) +
  # geom_ribbon(data = rmn_lac_avg,
  #           aes(fill = genotype,
  #               y = roll_mean,
  #               ymin = roll_mean - roll_sd,
  #               ymax = roll_mean + roll_sd),
  #           colour = NA,
  #           alpha = 0.25) +
  geom_line(data = rmn_lac_avg %>% filter(genotype == "WT" & cell_type == "MX"),
            aes(colour = cell_type,
                y = roll_scaled_cellu),
            size = 0.2) +
  labs(x = expression(paste("Wavenumber [", cm^-1,"]")),
       y = "Scaled scattering intensity") + 
  # scale_color_brewer(palette = "Set1", aesthetics = c("colour", "fill")) +
  scale_colour_manual(values = pal_pedersen_disc) +
  theme_leo() +
  theme(
    # legend.position = "bottom",
    legend.title = element_blank()
  ) +
  guides(colour = guide_legend(override.aes = list(alpha = 1, size = 1))) +
  facet_wrap(~genotype, ncol = 1)

# plotly::ggplotly(rmn_lac_test)
pdf("rmn_lac.pdf", height = onecol * 0.5, width = onecol * 1.5)
rmn_lac_test
dev.off()
```

## Lignin composition

```{r}

violin_data <- rmn_lac_sum %>%
  select(
    "Total lignin" = total_lignin,
    "S/G" = S.G,
    "P-units" = P_rel,
    AUC,
    # "Cellulose cryst." = cellu_cryst,
    "Benzaldehydes" = Benz_rel,
    # "P/cellulose" = P.cellu,
    # "G-units" = G_rel,
    # "Lignin/cellulose" = lig.cellu,
    "G-CHO/G-OH" = GCHO.GOH
  ) %>%
  filter(cell_type != "LP") %>%
  pivot_longer(
    cols = -c(genotype:replicate),
    names_to = "variable",
    values_to = "value"
  ) %>%
  mutate(cell_type = ordered(cell_type,
                             levels = c(
                               "IF",
                               "LP",
                               "XF",
                               "PX",
                               "MX"
                             )),
         genotype = ordered(genotype, levels = c(
           "WT",
           "Q-4",
           "Q-5",
           "Q-10",
           "Q-12",
           "Q-17",
           "Q"
         )),
         instance = case_when(replicate %in% c(1:5) ~ "1",
                              TRUE ~ "2"))

rmn_n <- rmn_lac_sum %>%
  group_by(genotype, replicate, cell_type) %>%
  summarise(n = n())

letters <- letter_groups(violin_data,
                         value,
                         genotype,
                         "tukey",
                         variable,
                         cell_type,
                         print_position = "above") %>%
  mutate(value = case_when(variable == "S/G" & cell_type %in% c("PX", "MX") ~
                             value + 1,
                           variable == "Total lignin" & cell_type == "MX" ~
                             value + 0.0005,
                           variable == "P-units" & cell_type == "MX" ~
                             value + 0.025,
                           TRUE ~ value))

lig_violin <- ggplot(
  violin_data,
  aes(
    x = genotype,
    y = value
  )
) +
  ggbeeswarm::geom_quasirandom(
    aes(colour = instance),
    size = 1,
    # dodge.width = 0.5,
    alpha = 0.5
  ) +
  # geom_violin(
  #   draw_quantiles = 0.5,
  #   fill = "white",
  #   colour = "black",
  #   alpha = 0.85,
  #   width = 0.2,
  #   # position = position_dodge(width = 0.5),
  #   size = 0.2,
  #   scale = "width"
  # ) +
  # geom_boxplot(
  #   # draw_quantiles = 0.5,
  #   outlier.alpha = 0,
  #   fill = "white",
  #   colour = "black",
  #   alpha = 0.85,
  #   width = 0.2,
  #   # position = position_dodge(width = 0.5),
  #   size = 0.2,
  #   fatten = 1
  # ) +
  geom_violin(
    draw_quantiles = 0.5,
    # outlier.alpha = 0,
    fill = "white",
    colour = "black",
    alpha = 0.85,
    width = 0.4,
    scale = "width",
    # position = position_dodge(width = 0.5),
    size = 0.2,
    # fatten = 1
  ) +
  geom_text(data = letters,
            aes(label = Letters),
            size = ggtext_size,
            family = "Helvetica") +
  scale_colour_manual(values = pal_ostwald_disc[c(1,3)]) +
  # scale_colour_brewer(palette = "Set1") +
  # scale_colour_viridis_d(drop = FALSE) +
  scale_x_discrete(drop = FALSE) +
  theme_leo() +
  theme(axis.title = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(hjust = 0.5, face = "plain"),
        legend.position = "bottom"
        ) +
  facet_grid(variable ~ cell_type, scales = "free_y", switch = "y")

pdf("lig_violin_complete.pdf", width = twocol, height = twocol)
lig_violin
dev.off()
```

## Multivariate analysis

```{r}
pca_data <- rmn_lac_sum %>%
  select(
    "Total lignin" = total_lignin,
    "S/G" = S.G,
    "P-units" = P_rel,
    AUC,
    # "Cellulose cryst." = cellu_cryst,
    "Benzaldehydes" = Benz_rel,
    # "P/cellulose" = P.cellu,
    "G-units" = G_rel,
    "S-units" = S_rel,
    "G-CHO/G-OH" = GCHO.GOH
  ) %>%
  filter(cell_type != "LP") %>%
  group_by(genotype, replicate, cell_type) %>%
  mutate(cell = row_number()) %>%
  pivot_wider(everything(), names_from = cell_type, values_from = c(4:11)) %>%
  unite("ID", genotype, replicate, cell)

pca_result <- prcomp(pca_data[, -1], center = TRUE, scale. = TRUE)
rownames(pca_result$x) <- pca_data$ID

# factoextra::fviz_pca_biplot(pca_result)

gg_pca <- as_tibble(pca_result$x, rownames = NA) %>%
  rownames_to_column(var = "ID") %>%
  separate(ID, sep = "_", into = c("genotype", "replicate", "cell"))

gg_pca_ellipse <- gg_pca %>%
  group_by(genotype) %>%
  summarise(PC1 = mean(PC1),
            PC2 = mean(PC2))

pdf("overall_PCA.pdf", width = onecol * 1.5, height = onecol)
ggplot(gg_pca, aes(x = PC1, y = PC2, fill = genotype)) +
  geom_hline(yintercept = 0, linetype = 1, size = 0.2) +
  geom_vline(xintercept = 0, linetype = 1, size = 0.2) +
  geom_point(
    size = 3,
    stroke = 0.4,
    alpha = 0.75,
    shape = 21
  ) +
  stat_ellipse(geom = "polygon", type = "t", level = 0.4) +
  geom_label_repel(data = gg_pca_ellipse, 
                   aes(label = genotype), 
                   # fill = NA,
                   size = ggtext_size * 1.5,
                   segment.alpha = 0,
                   label.size = NA,
                   family = "Helvetica") +
  # stat_ellipse(aes(fill = NULL), colour = "black", linetype = 2, size = 0.2) +
  # annotate("text",
  #   x = c(-35, 18, 7, -25),
  #   y = c(18, 25, -17, -25),
  #   label = c("Epidermis", "Vascular\nbundle", "Interfascicular\nfibre", "Pith"),
  #   family = "Helvetica",
  #   size = ggtext_size,
  #   hjust = 0
  # ) +
  labs(
    # x = "PC 1 [36.4 %]",
    # y = "PC 2 [19.5 %]",
    title = "Overall lignin"
  ) +
  scale_fill_viridis_d(alpha = 0.5) +
  theme_leo() +
  theme(
    plot.margin = unit(c(2, 2, 3, 2), "mm"),
    plot.title = element_text(size = 10)
  )
dev.off()

cell_type_pca <- function(celltype) {
  pca_data <- rmn_lac_sum %>%
  select(
    "Total lignin" = total_lignin,
    "S/G" = S.G,
    "P-units" = P_rel,
    AUC,
    # "Cellulose cryst." = cellu_cryst,
    "Benzaldehydes" = Benz_rel,
    # "P/cellulose" = P.cellu,
    "G-units" = G_rel,
    "S-units" = S_rel,
    "G-CHO/G-OH" = GCHO.GOH
  ) %>%
  filter(cell_type %in% celltype) %>%
  group_by(genotype, replicate, cell_type) %>%
  mutate(cell = row_number()) %>%
  pivot_wider(everything(), names_from = cell_type, values_from = c(4:11)) %>%
  unite("ID", genotype, replicate, cell)

pca_result <- prcomp(pca_data[, -1], center = TRUE, scale. = TRUE)
rownames(pca_result$x) <- pca_data$ID

# factoextra::fviz_pca_biplot(pca_result)

gg_pca <- as_tibble(pca_result$x, rownames = NA) %>%
  rownames_to_column(var = "ID") %>%
  separate(ID, sep = "_", into = c("genotype", "replicate", "cell"))

gg_pca_ellipse <- gg_pca %>%
  group_by(genotype) %>%
  summarise(PC1 = mean(PC1),
            PC2 = mean(PC2))

ggplot(gg_pca, aes(x = PC1, y = PC2, fill = genotype)) +
  geom_hline(yintercept = 0, linetype = 1, size = 0.2) +
  geom_vline(xintercept = 0, linetype = 1, size = 0.2) +
  geom_point(
    size = 1,
    stroke = 0.2,
    alpha = 0.75,
    shape = 21
  ) +
  stat_ellipse(geom = "polygon", type = "t", level = 0.4) +
  geom_label_repel(data = gg_pca_ellipse, 
                   aes(label = genotype,
                       fill = genotype), 
                   size = ggtext_size,
                   segment.alpha = 0,
                   label.size = NA,
                   family = "Helvetica") +
  # stat_ellipse(aes(fill = NULL), colour = "black", linetype = 2, size = 0.2) +
  # annotate("text",
  #   x = c(-35, 18, 7, -25),
  #   y = c(18, 25, -17, -25),
  #   label = c("Epidermis", "Vascular\nbundle", "Interfascicular\nfibre", "Pith"),
  #   family = "Helvetica",
  #   size = ggtext_size,
  #   hjust = 0
  # ) +
  labs(
    # x = "PC 1 [36.4 %]",
    # y = "PC 2 [19.5 %]",
    title = celltype
  ) +
  scale_fill_viridis_d(alpha = 0.5) +
  theme_leo() +
  theme(
    plot.margin = unit(c(2, 2, 3, 2), "mm"),
    plot.title = element_text(size = 10)
  )
}

pdf("celltype_PCAs.pdf", width = onecol * 1.5, height = onecol)
cell_type_pca("PX") + cell_type_pca("MX") + cell_type_pca("XF") + cell_type_pca("IF")
dev.off()

# corr_data <- rmn_lac_sum %>%
#   select(
#     "Total lignin" = total_lignin,
#     "S/G" = S.G,
#     "P-units" = P_rel,
#     AUC,
#     # "Cellulose cryst." = cellu_cryst,
#     "Benzaldehydes" = Benz_rel,
#     # "P/cellulose" = P.cellu,
#     "G-units" = G_rel,
#     "S-units" = S_rel,
#     "G-CHO/G-OH" = GCHO.GOH
#   ) %>%
#   filter(cell_type != "LP") %>%
#   group_by(genotype, replicate, cell_type) %>%
#   mutate(cell = row_number()) %>%
#   pivot_wider(everything(), names_from = cell_type, values_from = c(4:11)) %>%
#   unite("ID", genotype, replicate, cell) %>%
#   column_to_rownames(., var = "ID")
# 
# pdf("lignin_corr.pdf")
# corrplot::corrplot.mixed(cor(as.matrix(corr_data)))
# dev.off()
```
