---
title: "TE activity"
author: "Leonard Blaschek"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(showtext)

pal_ostwald_cont <- c(
  "#155DA7",
  "#0A75B9",
  # "#0C89C9",
  "#FED32F",
  # "#F8A63A",
  "#EF663A",
  "#ED4137"
)

#### import Helvetica ####
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 6,
                      base_family = "Helvetica") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, 
                                # face = "italic"
                                ),
      axis.ticks = element_line(
        size = 0.125,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        size = 6,
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        size = 6,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_text(
        colour = "black",
        size = 6
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 6),
      legend.key.height = unit(4, "mm"),
      plot.title = element_text(
        size = 6,
        hjust = 0
      ),
      complete = TRUE
    )
}

ggtext_size <- 6 / (14 / 5)
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54
```


## Load viability and differentiation data

```{r}

growth_files <-
  list.files(
    path = "/home/leonard/Dropbox/2021-01_inductions/",
    pattern = "*.txt",
    recursive = FALSE,
    full.names = TRUE
  )

read_plus <- function(flnm) {
  read_tsv(flnm,
    comment = "#",
    col_names = "code",
    col_types = "c",
    # locale = locale(decimal_mark = ",")
  ) %>%
    mutate(filename = basename(flnm)) %>%
    separate(filename, into = c("date", "replicate", "dpi", "treatment"), sep = "_") %>%
    mutate(replicate = str_remove(replicate, fixed("R")),
           dpi = as.numeric(str_remove(dpi, fixed("d"))),
           treatment = str_remove(treatment, fixed(".txt")))
}
  
  
growth_data <- map(growth_files, read_plus) %>%
  bind_rows() %>%
  mutate(
    n = str_length(code),
    nTEs_alive = str_count(code, "k"),
    nTEs_dead = str_count(code, "l"),
    TEs_alive = str_count(code, "i"),
    TEs_dead = str_count(code, "o"),
    nTE_viab = nTEs_alive / (nTEs_alive + nTEs_dead),
    TE_prop = (TEs_alive + TEs_dead) / n,
    TE_viab = TEs_alive / (TEs_alive + TEs_dead)
  )

growth_avg <- growth_data %>%
  group_by(treatment, dpi) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))
```

## Plot differentiation curves

```{r}

growth <- ggplot(growth_data) +
  geom_tile(data = growth_avg,
                aes(x = dpi,
                    y = TE_prop,
                    fill = nTE_viab),
               width = 1,
               height = Inf,
            alpha = 0.75) +
  geom_point(aes(x = dpi,
                 y = TE_prop,
                 fill = TE_viab),
             size = 3,
             shape = 21,
             stroke = 0.2) +
  geom_line(data = growth_avg,
            (aes(x = dpi,
                 y = TE_prop))) +
  scale_fill_gradientn(colours = pal_ostwald_cont, trans = "reverse", name = "Viability", limits = c(1, 0)) +
  scale_x_continuous(limits = c(2.5, 9.5), expand = expansion(add = 0)) +
  labs(x = "Days past induction",
       y = "TE proportion") +
  theme_leo() +
  theme(legend.position = "bottom")

pdf("TE_growth.pdf", width = onecol, height = onecol)
growth
dev.off()
  

```
