---
title: "C4H Raman"
author: "Leonard Blaschek"
date: "01/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(showtext)
library(colorspace)
library(ggrepel)
library(broom)
library(ggbeeswarm)
library(tukeygrps)
library(baseline)
library(patchwork)

pal_ostwald_cont <- c(
  "#155DA7",
  "#0A75B9",
  # "#0C89C9",
  "#FED32F",
  # "#F8A63A",
  "#EF663A",
  "#ED4137"
)

pal_ostwald_disc <- c(
  "#275d95",
  "#e8c245",
  "#d25952"
)

pal_ostwald_disc_long <- c(
  "#8fab1d",
  "#2d7d73",
  "#1d566f",
  "#275d95",
  "#e8c245",
  "#d25952"
)

pal_flame <- c(
  "#1F265D",
  "#203F8F",
  "#404678",
  "#897B88",
  "#E7BBA2",
  "#FFEDC3",
  "#FEFEFE"
)

pal_flame_disc <- c(
  "#ffedc3",
  "#897b88",
  "#1f265d"
)

# import Helvetica
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

# generating plot theme
theme_leo <- function(base_size = 6,
                      base_family = "Helvetica") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      axis.ticks = element_line(
        size = 0.125,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        size = 6,
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        size = 6,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_text(
        colour = "black",
        size = 6
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      axis.line = element_line(size = 0.2),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 6),
      legend.key.height = unit(4, "mm"),
      plot.title = element_text(
        size = 6,
        hjust = 0
      ),
      complete = TRUE
    )
}

ggtext_size <- 6 / (14 / 5)
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54
```

## import and tidy *Arabidopsis* Raman data

```{r}
rmn_files <-
  list.files(
    path = "/run/media/leonard/LEONARD/C4H/spectra/",
    pattern = "*.txt",
    recursive = TRUE,
    full.names = TRUE
  )

read_plus <- function(flnm) {
  read_tsv(flnm,
           comment = "#",
           col_names = c("wavenumber", "intensity"),
           col_types = "cc",
           # locale = locale(decimal_mark = ",")
  ) %>%
    mutate(
      flnm = str_remove(basename(flnm), fixed(".txt"))
      ) %>%
    separate(flnm, into = c("genotype", "replicate", "cell_type", "cell", "layer"), sep = "_") %>%
    mutate(
      wavenumber = as.numeric(str_replace(wavenumber, fixed(","), fixed("."))),
      # wavenumber = case_when(genotype == "WT" & replicate == 1 ~ wavenumber,
      #                        TRUE ~ wavenumber + 33),
      intensity = as.numeric(str_replace(intensity, fixed(","), fixed("."))),
      layer = case_when(is.na(layer) ~ "full",
                        TRUE ~ layer)
    ) %>%
    pivot_wider(
      id_cols = c(genotype, replicate, cell_type, cell, layer),
      names_from = wavenumber,
      values_from = intensity
    ) %>%
    group_by(genotype, replicate, cell_type, cell, layer) %>%
    nest()
}

rmn_c4h <- lapply(rmn_files, read_plus) %>%
  bind_rows() 

#### baseline correction ####
rmn_als <- function(x) {
  corrected_spectra <- baseline.als(as.matrix(x),
                                    lambda = 5,
                                    p = 0.01,
                                    maxit = 100
  )
  
  as_tibble(corrected_spectra$corrected, rownames = NA)
}

rmn_c4h_corrected <- rmn_c4h %>%
  mutate(corrected_data = map(data, rmn_als)) %>%
  select(-data) %>%
  unnest(cols = corrected_data) %>%
  pivot_longer(-c(genotype:layer),
               names_to = "wavenumber",
               values_to = "corrected.intensity"
  ) %>%
  drop_na() %>%
  mutate(wavenumber = as.numeric(wavenumber))

#### filtering and scaling ####

# rough alignment (30 cm-1 shift)
lig_peak <- rmn_c4h_corrected %>%
  unite("ID", 
        genotype, replicate, cell_type, cell, layer,
        remove = F,
        sep = "_") %>%
  filter(round(wavenumber, digits = 0) %in% c(1560:1640)) %>%
  group_by(genotype, replicate, cell_type, cell, layer) %>%
  mutate(
    peak_pos = case_when(ID == "cmp_2_PX_1_full" ~ 1570.57,
                         ID == "c4h_1_LP_1_full" ~ 1570.50,
                         TRUE ~ wavenumber[which.max(corrected.intensity)])
  ) %>%
  select(-wavenumber, -corrected.intensity) %>%
  unique() %>%
  ungroup() %>%
  mutate(peak_pos_ref = 1598)

rmn_c4h_aligned_rough <- rmn_c4h_corrected %>%
  left_join(lig_peak) %>%
  group_by(genotype, replicate, cell_type, cell, wavenumber,layer) %>%
  mutate(wavenumber = wavenumber + (peak_pos_ref - peak_pos)) 

rmn_c4h_scaled <- rmn_c4h_aligned_rough %>%
  filter(wavenumber > 200 & wavenumber < 1700) %>%
  group_by(genotype, replicate, cell_type, cell, layer) %>%
  mutate(
    AUC = MESS::auc(wavenumber, corrected.intensity),
    scaled = corrected.intensity / AUC,
    scaled_lig = corrected.intensity / (
      (corrected.intensity[abs(wavenumber - 1603) == min(abs(wavenumber - 1603))] / 2) + corrected.intensity[abs(wavenumber - 1334) == min(abs(wavenumber - 1334))]
    )
  ) %>% 
  filter(cell_type != "PA")

rmn_c4h_values <- rmn_c4h_scaled %>%
  group_by(genotype, cell_type, replicate, cell) %>%
  summarise(raw_995 = corrected.intensity[abs(wavenumber - 995) == min(abs(wavenumber - 995))][1],
            scaled_995 = scaled[abs(wavenumber - 995) == min(abs(wavenumber - 995))][1])

rmn_max <- rmn_c4h_scaled %>%
  group_by(genotype, replicate, cell, cell_type) %>%
  summarise (peak_position = wavenumber[which.max(scaled)])
```

## export *Arabidopsis*
```{r}

rmn_c4h_raw <- rmn_c4h_scaled %>%
  group_by(genotype, replicate, cell_type, cell, layer) %>%
  select(wavenumber, corrected.intensity) %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  complete(wavenumber = seq(200, 1700, 0.1)) %>%
  arrange(wavenumber) %>%
  mutate(moving_mean = 
           RcppRoll::roll_mean(corrected.intensity, n = 30, fill = NA, na.rm = TRUE)
         ) %>%
  filter(wavenumber %% 1 %in% c(0, 0.5)) %>%
  # filter(wavenumber %in% round(rmn_pop_scaled$wavenumber, digits = 1)) %>%
  pivot_wider(id_cols = c(genotype, replicate, cell_type, layer, cell),
              names_from = wavenumber,
              values_from = moving_mean)

rmn_c4h_auc <- rmn_c4h_scaled %>%
  group_by(genotype, replicate, cell_type, cell, layer) %>%
  select(wavenumber, scaled) %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  complete(wavenumber = seq(200, 1700, 0.1)) %>%
  arrange(wavenumber) %>%
  mutate(moving_mean = 
           RcppRoll::roll_mean(scaled, n = 30, fill = NA, na.rm = TRUE)
         ) %>%
  filter(wavenumber %% 1 %in% c(0, 0.5)) %>%
  # filter(wavenumber %in% round(rmn_pop_scaled$wavenumber, digits = 1)) %>%
  pivot_wider(id_cols = c(genotype, replicate, cell_type, layer, cell),
              names_from = wavenumber,
              values_from = moving_mean)


# write_excel_csv(rmn_c4h_values, "Raman_c4h_995.csv")
write_excel_csv(rmn_c4h_raw, "Raman_Atc4h_raw.csv")
write_excel_csv(rmn_c4h_auc, "Raman_Atc4h_scaled.csv")
```

## import and tidy poplar Raman data

```{r}
rmn_files <-
  list.files(
    path = "/data/PhD/IRX/Poplar/2020-08_soil_poplar",
    pattern = "(TE|FI|RP)(.*).txt",
    recursive = TRUE,
    full.names = TRUE
  )

read_plus <- function(flnm) {
  read_tsv(flnm,
    comment = "#",
    col_names = c("wavenumber", "intensity"),
    col_types = "cc",
    # locale = locale(decimal_mark = ",")
  ) %>%
    mutate(
      filename = str_remove(
        flnm,
        fixed("/data/PhD/IRX/Poplar/2020-08_soil_poplar/")
      )
    ) %>%
    separate(filename, into = c("genotype", "replicate", "cell"), sep = "([/-])") %>%
    mutate(
      wavenumber = as.numeric(str_replace(wavenumber, fixed(","), fixed("."))),
      intensity = as.numeric(str_replace(intensity, fixed(","), fixed("."))),
      cell = str_remove(cell, fixed(".txt")),
      technical = unlist(str_extract_all(cell, "[:alpha:]+")),
      cell = unlist(str_extract_all(cell, "[:digit:]+")),
      cell_type = case_when(str_detect(technical, "TE") ~ "TE",
                            str_detect(technical, "FI") ~ "fibre",
                            TRUE ~ "ray")
    ) %>%
    pivot_wider(
      id_cols = c(genotype, replicate, technical, cell_type, cell),
      names_from = wavenumber,
      values_from = intensity
    ) %>%
    group_by(genotype, replicate, technical, cell_type, cell) %>%
    nest()
}

exclude <- read_csv("/data/PhD/IRX/Poplar/2020-08_soil_poplar/pop_rmn_exclude.csv",
                     col_types = "cccc") %>%
  mutate(cell_type = "TE") %>%
  rename("cell" = "TE")

rmn_pop <- lapply(rmn_files, read_plus) %>%
  bind_rows() %>%
  anti_join(exclude)

#### baseline correction ####
rmn_als <- function(x) {
  corrected_spectra <- baseline.als(as.matrix(x),
    lambda = 5,
    p = 0.01,
    maxit = 100
  )

  as_tibble(corrected_spectra$corrected, rownames = NA)
}

rmn_pop_corrected <- rmn_pop %>%
  mutate(corrected_data = map(data, rmn_als)) %>%
  select(-data) %>%
  unnest() %>%
  pivot_longer(-c(genotype, replicate, technical, cell_type, cell),
    names_to = "wavenumber",
    values_to = "corrected.intensity"
  ) %>%
  drop_na() %>%
  mutate(wavenumber = as.numeric(wavenumber))


#### filtering and scaling ####

# rough alignment (30 cm-1 shift)
lig_peak <- rmn_pop_corrected %>%
  unite("ID", 
        genotype, replicate, technical, cell_type, cell, 
        remove = F,
        sep = "_") %>%
  filter(round(wavenumber, digits = 0) %in% c(1560:1640)) %>%
  group_by(genotype, replicate, technical, cell_type, cell) %>%
  mutate(
    peak_pos = wavenumber[which.max(corrected.intensity)]
  ) %>%
  select(-wavenumber, -corrected.intensity) %>%
  unique() %>%
  ungroup() %>%
  mutate(peak_pos_ref = case_when(genotype == "T89" & cell_type == "TE" ~ 
                                    peak_pos[ID =="T89_4_alignedTE_TE_1"],
                                  genotype == "T89" & cell_type == "fibre" ~
                                    peak_pos[ID =="T89_4_FI_fibre_1"],
                                  genotype == "CCR1" & cell_type == "TE" ~
                                    peak_pos[ID =="T89_4_alignedTE_TE_1"],
                                  genotype == "CCR1" & cell_type == "fibre" ~
                                    peak_pos[ID =="T89_4_FI_fibre_1"],
                                  genotype == "C4H" & cell_type == "TE" ~
                                    peak_pos[ID =="C4H_4_cTE_TE_1"],
                                  genotype == "C4H" & cell_type == "fibre" ~
                                    peak_pos[ID =="C4H_4_cFI_fibre_3"],
                                  TRUE ~ 0)
  )

rmn_pop_aligned_rough <- rmn_pop_corrected %>%
  left_join(lig_peak) %>%
  group_by(genotype, replicate, technical, cell_type, cell, wavenumber) %>%
  mutate(wavenumber = wavenumber + (peak_pos_ref - peak_pos)) 

rmn_pop_scaled <- rmn_pop_aligned_rough %>%
  group_by(genotype, replicate, technical, cell_type, cell) %>%
  mutate(
    # wavenumber = case_when(genotype == "C4H" & replicate == 4 ~ wavenumber,
    #                        genotype == "T89" & technical == "alignedTE" ~ wavenumber,
    #                        cell_type == "fibre" | cell_type == "ray" ~ wavenumber,
    #                        TRUE ~ wavenumber + 33),
    AUC = MESS::auc(wavenumber, corrected.intensity),
    scaled = corrected.intensity / AUC,
    scaled_lig = corrected.intensity / (
      (corrected.intensity[abs(wavenumber - 1603) == min(abs(wavenumber - 1603))] / 2) + corrected.intensity[abs(wavenumber - 1334) == min(abs(wavenumber - 1334))]
    )
  ) %>%
  filter(wavenumber > 200 & wavenumber < 1700)

celltypes <- read_csv(
  "/data/PhD/IRX/Poplar/2020-08_soil_poplar/poplar_cell_types.csv",
  col_types = "cccccc") %>%
  select(-n_v, "vessel_type" = "cell_type")

rmn_pop_scaled <- rmn_pop_scaled %>%
  left_join(celltypes,
            by = c("genotype", "replicate", "technical", "cell" = "TE")) 
```


## export poplar
```{r}

rmn_c4h_raw <- rmn_pop_scaled %>%
  group_by(genotype, replicate, technical, cell_type, cell, vessel_type) %>%
  select(wavenumber, corrected.intensity) %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  complete(wavenumber = seq(200, 1700, 0.1)) %>%
  arrange(wavenumber) %>%
  mutate(moving_mean = 
           RcppRoll::roll_mean(corrected.intensity, n = 30, fill = NA, na.rm = TRUE)
         ) %>%
  filter(wavenumber %% 1 %in% c(0, 0.5)) %>%
  # filter(wavenumber %in% round(rmn_pop_scaled$wavenumber, digits = 1)) %>%
  pivot_wider(id_cols = c(genotype, replicate, technical, cell_type, vessel_type, cell),
              names_from = wavenumber,
              values_from = moving_mean)

# rmn_c4h_raw <- rmn_c4h_raw %>%
#   select(genotype, replicate, technical, cell_type, vessel_type, cell, order(as.numeric(colnames(.))))

rmn_c4h_auc <- rmn_pop_scaled %>%
  group_by(genotype, replicate, technical, cell_type, cell, vessel_type) %>%
  select(wavenumber, scaled) %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  complete(wavenumber = seq(200, 1700, 0.1)) %>%
  arrange(wavenumber) %>%
  mutate(moving_mean = 
           RcppRoll::roll_mean(scaled, n = 30, fill = NA, na.rm = TRUE)
         ) %>%
  filter(wavenumber %% 1 %in% c(0, 0.5)) %>%
  # filter(wavenumber %in% round(rmn_pop_scaled$wavenumber, digits = 1)) %>%
  pivot_wider(id_cols = c(genotype, replicate, technical, cell_type, vessel_type, cell),
              names_from = wavenumber,
              values_from = moving_mean)

# rmn_c4h_auc <- rmn_c4h_auc %>%
#   select(genotype, replicate, technical, cell_type, vessel_type, cell, order(as.numeric(colnames(.))))

# write_excel_csv(rmn_c4h_values, "Raman_c4h_995.csv")
write_excel_csv(rmn_c4h_raw, "Raman_Ptc4h_raw.csv")
write_excel_csv(rmn_c4h_auc, "Raman_Ptc4h_scaled.csv")
```

## plot *Arabidopsis*

```{r}

rmn_c4h_raw <- rmn_c4h_scaled %>%
  group_by(genotype, replicate, cell_type, cell, layer) %>%
  select(wavenumber, corrected.intensity) %>%
  mutate(wavenumber = round(wavenumber, digits = 1)) %>%
  complete(wavenumber = seq(200, 1700, 0.1)) %>%
  arrange(wavenumber) %>%
  mutate(moving_mean = 
           RcppRoll::roll_mean(corrected.intensity, n = 30, fill = NA, na.rm = TRUE)
         ) %>%
  filter(wavenumber %% 1 %in% c(0, 0.5))


c4h_celltypes <- ggplot(rmn_c4h_raw,
                        # aes(x = wavenumber,
                        #     y = mean.intensity,
                        #     colour = cell_type)
                        ) +
  geom_vline(xintercept = 993,
             linetype = 2,
             size = 0.1) +
  ggridges::geom_ridgeline(
    aes(x = wavenumber,
        y = reorder(cell_type, -moving_mean),
        height = moving_mean,
        fill = reorder(cell_type, -moving_mean),
        group = interaction(genotype, cell_type, replicate, cell)
        ),
    min_height = -200,
    scale = 100,
    size = 0.1,
    alpha = 0.75,
    colour = rgb(0,0,0,0.5)
  ) +
  # geom_line(size = 0.2,
  #           alpha = 0.75) +
  theme_leo() +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  # scale_colour_brewer(palette = "Dark2") +
  scale_fill_viridis_d() +
  scale_x_continuous(trans = "reverse") +
  labs(x = "Wavenumber",
       y ="Intensity (baseline corrected)") +
  facet_wrap(~genotype)

# c4h_celltypes_scaled <- ggplot(rmn_c4h_scaled,
#                         # aes(x = wavenumber,
#                         #     y = mean.intensity,
#                         #     colour = cell_type)
# ) +
#   geom_vline(xintercept = 995,
#              linetype = 2,
#              size = 0.2) +
#   ggridges::geom_ridgeline(
#     aes(x = wavenumber,
#         y = reorder(cell_type, -corrected.intensity),
#         height = scaled,
#         fill = reorder(cell_type, -corrected.intensity),
#         group = interaction(genotype, cell_type, replicate, cell)
#         ),
#     min_height = -0.02,
#     scale = 200,
#     size = 0.2,
#     alpha = 0.75
#   ) +
#   # geom_line(size = 0.2,
#   #           alpha = 0.75) +
#   theme_leo() +
#   theme(legend.position = "bottom",
#         legend.title = element_blank()) +
#   # scale_colour_brewer(palette = "Dark2") +
#   scale_fill_viridis_d() +
#   scale_x_continuous(trans = "reverse") +
#   labs(x = "Wavenumber",
#        y ="Intensity (corrected and scaled to AUC)") +
#   facet_wrap(~genotype)

# layers <- ggplot(rmn_c4h_scaled %>% filter(cell_type == "IF"),
#        aes(x = wavenumber,
#            y = corrected.intensity,
#            colour = layer)) +
#   geom_vline(xintercept = 995,
#              linetype = 2,
#              size = 0.2) +
#   geom_line(aes(group = interaction(layer, replicate, cell)),
#             size = 0.2,
#             alpha = 0.75) +
#   theme_leo() +
#   theme(legend.position = "bottom") +
#   scale_x_continuous(trans = "reverse") +
#   scale_colour_manual(values = pal_ostwald_disc) +
#   facet_wrap(~genotype)
# 
# rmn_box <- function(y) {
#   y <- enquo(y)
#   letters <- letter_groups(
#     rmn_c4h_values %>% filter(cell_type != "PA"),
#     !!y,
#     genotype,
#     "tukey",
#     cell_type,
#     print_position = "above"
#   )
#   
#   ggplot(rmn_c4h_values %>% filter(cell_type != "PA"),
#                      aes(x = genotype,
#                          y = !!y)) +
#   geom_quasirandom(
#     shape = 16,
#     alpha = 0.5,
#     groupOnX = TRUE,
#     width = 0.2) +
#   # stat_summary(
#   #   fun = mean,
#   #   fun.min = mean,
#   #   fun.max = mean,
#   #   geom = "crossbar",
#   #   width = 0.5,
#   #   size = 0.5,
#   #   colour = pal_ostwald_disc[3],
#   #   fatten = 0
#   # ) +
#   geom_boxplot(
#     fill = "white",
#     colour = "black",
#     alpha = 0.85,
#     outlier.alpha = 0,
#     width = 0.2,
#     size = 0.2,
#   ) +
#     geom_text(data = letters,
#               aes(label = Letters),
#               family = "Helvetica",
#               size = ggtext_size) +
#   # geom_violin(
#   #   draw_quantiles = 0.5,
#   #   fill = "white",
#   #   colour = "black",
#   #   alpha = 0.85,
#   #   width = 0.2,
#   #   size = 0.2,
#   #   scale = "width") +
#   theme_leo() +
#   theme(axis.title.x = element_blank()) +
#   facet_wrap(~cell_type, ncol = 5)
# }
# 
# raw <- rmn_box(raw_995) + labs(y = "Corrected intensity")
# scaled <- rmn_box(scaled_995) + labs(y = "AUC-scaled intensity")
# 
# patch <-raw + scaled


pdf("rmn_c4h.pdf", width = twocol, height = onecol)
c4h_celltypes
# layers
# patch +
#   plot_annotation(
#     tag_levels = "A"
#   ) &
#   theme(plot.tag = element_text(size = 10, face = "bold", family = "Helvetica")) &
#   plot_layout(ncol = 1)
dev.off()
```

## plot poplar

```{r}

# rmn_c4h_filled <- rmn_pop_scaled %>%
#   group_by(genotype, replicate, technical, cell_type, cell, vessel_type) %>%
#   select(wavenumber, corrected.intensity) %>%
#   mutate(wavenumber = round(wavenumber, digits = 1)) %>%
#   complete(wavenumber = seq(200, 1700, 0.1)) %>%
#   arrange(wavenumber) %>%
#   mutate(moving_mean = 
#            RcppRoll::roll_mean(corrected.intensity, n = 30, fill = NA, na.rm = TRUE)
#          ) %>%
#   filter(wavenumber %% 1 %in% c(0, 0.5))
# 
# rmn_filled_plot <- rmn_c4h_filled %>%
#   filter(cell_type != "ray") %>%
#   group_by(genotype, replicate, technical, cell_type, cell, vessel_type) %>%
#   mutate(ind_mean = mean(moving_mean, na.rm = TRUE)) %>%
#   group_by(genotype, cell_type, vessel_type) %>%
#   mutate(overall_mean = mean(moving_mean, na.rm = TRUE),
#          typical = case_when(
#            abs(overall_mean - ind_mean) == min(abs(overall_mean - ind_mean)) ~ "yes",
#            TRUE ~ "no"))
# 
# rmn_filled <- ggplot(rmn_c4h_filled,
#                      aes(x = wavenumber,
#                          y = moving_mean,
#                          colour = genotype)) +
#   geom_line(aes(
#     group = interaction(genotype, replicate, technical, cell)
#   ),
#   alpha = 0.05,
#   size = 0.1
#   ) +
#   geom_line(data = filter(rmn_filled_plot, typical == "yes")) +
#   scale_colour_manual(values = pal_ostwald_disc[c(3, 2, 1)]) +
#   theme_leo() +
#   theme(
#     legend.position = "bottom",
#     legend.title = element_blank()
#   ) +
#   guides(colour = guide_legend(override.aes = list(alpha = 1, size = 1))) +
#   facet_wrap(vessel_type~cell_type, ncol = 1) +
#   scale_x_continuous(trans = "reverse") +
#   geom_vline(xintercept = c(1600, 1334, 1120, 1095, 1000, 381))
# 
# rmn_pop_plot <- rmn_pop_scaled %>%
#   filter(cell_type != "ray") %>%
#   group_by(genotype, replicate, technical, cell_type, cell, vessel_type) %>%
#   mutate(ind_mean = mean(scaled)) %>%
#   group_by(genotype, cell_type, vessel_type) %>%
#   mutate(overall_mean = mean(scaled),
#          typical = case_when(
#            abs(overall_mean - ind_mean) == min(abs(overall_mean - ind_mean)) ~ "yes",
#            TRUE ~ "no"))
# %>%
#   mutate(wavenumber = round(wavenumber, digits = 0)) %>%
#   select(genotype, cell_type, replicate, technical, cell, wavenumber, scaled) %>%
#   arrange(desc(wavenumber)) %>%
#   group_by(genotype, cell_type, replicate, technical, cell) %>%
#   mutate(rollmean = zoo::rollapplyr(scaled, 3, mean, partial=TRUE, fill = NA)) %>%
#   group_by(genotype, cell_type, wavenumber) %>%
#   mutate(mean = mean(rollmean))

rmn_pop_test <- ggplot(
  rmn_pop_plot,
  aes(
    x = wavenumber,
    y = scaled,
    colour = genotype
  )
) +
  scale_x_continuous(trans = "reverse") +
  geom_vline(xintercept = c(1600, 1334, 1120, 1095, 1000, 381)) +
  # geom_line(data = filter(rmn_pop_scaled, genotype == "C4H"),
  #           aes(group = interaction(genotype, replicate, technical, TE),
  #               colour = replicate),
  #           alpha = 0.25,
  #           size = 0.1) +
  geom_line(aes(
    group = interaction(genotype, replicate, technical, cell)
  ),
  alpha = 0.05,
  size = 0.1
  ) +
  # geom_line(aes(y = mean)) +
  # geom_smooth(method = lm, formula = y ~ splines::bs(x, 20), se = FALSE) +
  # ggformula::geom_spline(nknots = 800) +
  geom_line(data = filter(rmn_pop_plot, typical == "yes")) +
  # geom_line(data = data.frame(
  #   spline(
  #     rmn_pop_avg$wavenumber[rmn_pop_avg$genotype == "T89"],
  #     rmn_pop_avg$mean[rmn_pop_avg$genotype == "T89"],
  #     n = 1500)
  #   ),
  #   aes(x = x,
  #       y = y),
  #   colour = pal_ostwald_disc[1],
  #   alpha = 0.75) +
  # geom_line(data = data.frame(
  #   spline(
  #     rmn_pop_avg$wavenumber[rmn_pop_avg$genotype == "CCR1"],
  #     rmn_pop_avg$mean[rmn_pop_avg$genotype == "CCR1"],
  #     n = 1500)
  #   ),
  #   aes(x = x,
  #       y = y),
  #   colour = pal_ostwald_disc[2],
  #   alpha = 0.75) +
  # geom_line(data = data.frame(
  #   spline(
  #     rmn_pop_avg$wavenumber[rmn_pop_avg$genotype == "C4H"],
  #     rmn_pop_avg$mean[rmn_pop_avg$genotype == "C4H"],
  #     n = 1500)
  #   ),
  #   aes(x = x,
  #       y = y),
  #   colour = pal_ostwald_disc[3],
  #   alpha = 0.75) +
  scale_colour_manual(values = pal_ostwald_disc[c(3, 2, 1)]) +
  theme_leo() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  guides(colour = guide_legend(override.aes = list(alpha = 1, size = 1))) +
  facet_wrap(vessel_type~cell_type, ncol = 1)

# plotly::ggplotly(rmn_pop_test)

pdf("rmn_pop.pdf", height = 5)
rmn_pop_test
dev.off()
```