---
title: "CML Wiesner analysis"
author: "Leonard Blaschek"
date: "17 May 2019"
output: html_document
# output: 
#   pdf_document:
#     latex_engine: lualatex
#     fig_caption: yes
#     fig_height: 6
#     includes:
#       in_header: rmd_temp.tex
# sansfont: Helvetica Neue LT Std
# monofont: Inconsolata
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(showtext)
# library(lazyeval)
library(agricolae)
library(ggthemes)
library(ggbeeswarm)
library(cowplot)
library(tidyverse)
# library(gghighlight)

#### import Helvetica Neue ####
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

# generating plot theme
theme_leo <- function(base_size = 8,
                      base_family = "Helvetica") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      axis.ticks = element_line(
        size = 0.2,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        size = 8,
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        size = 8,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_text(
        colour = "black",
        size = 8
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.2),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 8),
      legend.key.height = unit(4, "mm"),
      legend.margin = unit(c(0, 0, 0, 0), "mm"),
      plot.margin = unit(c(2, 2, 2, 2), "mm"),
      complete = TRUE
    )
}

update_geom_defaults("line", list(size = 0.2))
update_geom_defaults("segment", list(size = 0.2))

scale_range <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}
scale_z <- function(x) {
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
}
scale_max <- function(x) {
  x / max(x)
}
# scale_lig <- function(x) {
#   x / max(x[wavenumber > 1590 & wavenumber < 1610])
# }

# dimensions
twocol <- 16.6 / 2.54
onehalfcol <- 12.5 / 2.54
onecol <- 8 / 2.54
ggtext_size <- 8 / (14 / 5)


tukey <- function(x) {
  aov1 <- aov(data = x, hue ~ genotype)
  groups <- HSD.test(aov1, "genotype", alpha = 0.001)
  groups$groups[["genotype"]] <- rownames(groups$groups)
  groups$groups[["hue"]] <- -0.05
  return(groups[["groups"]])
}
```

## Load measurements

```{r load data, fig.showtext = TRUE, out.width = '100%', message = FALSE}

cml_hue_files <-
  list.files(
    path = "/home/leonard/Documents/Uni/Phloroglucinol/19-05-31_warped_images/hue/",
    pattern = ".csv",
    recursive = FALSE,
    full.names = TRUE
  )

read_plus <- function(flnm) {
  read_csv(flnm) %>%
    add_column(filename = flnm, .before = 1) %>%
    rename("distance" = X1)
}

cml_data <- lapply(cml_hue_files, read_plus) %>%
  bind_rows()

cml_data <- cml_data %>%
  mutate(filename = str_remove(basename(filename), fixed("_warped.tiff.csv")),
         filename = str_remove(filename, fixed("_50"))) %>%
  separate(filename, into = c("genotype", "replicate", "condition", "technical", "format"), sep = "([\\.\\_])") %>%
  mutate(technical = str_replace(technical, fixed("jpg"), "I"),
         technical = str_replace(technical, fixed("tif"), "I")) %>%
  select(-format, -condition) %>%
  gather(
    key = "ROI",
    value = "hue",
    -genotype,
    -replicate,
    -technical,
    -distance
  ) %>%
  mutate(
    ROI = str_replace(ROI, "Roi_", ""),
    hue = na_if(hue, 0) / 255 * 360,
    replicate = as.character(replicate),
    genotype = recode(genotype, "Col-0" = "WT",
                      "cad" = "cad4xcad5",
                      "omt" = "omt1",
                      "fah" = "fah1",
                      "ccoaomt" = "ccoaomt1",
                      "4cl1x2" = "4cl1x4cl2"),
    genotype = ordered(genotype, levels = c(
      "WT",
      "4cl1",
      "4cl2",
      "4cl1x4cl2",
      "ccoaomt1",
      "fah1",
      "omt1",
      "ccr1-3",
      "cad4",
      "cad5",
      "cad4xcad5"
    ))
  ) %>%
  drop_na() %>%
  group_by(genotype, replicate, technical, ROI) %>%
  mutate(
    distance = 1:n(),
    # distance.scaled = scale(distance, center = TRUE, scale = TRUE),
    distance.scaled = scale_range(distance),
    hue.scaled = scale(hue, center = FALSE, scale = TRUE),
    # hue.scaled = scale_range(hue)
  )

cml_data_avg <- cml_data %>%
  ungroup() %>%
  group_by(genotype) %>%
  summarise(a.median = median(hue))

cml_data <- cml_data %>%
  left_join(cml_data_avg, by = "genotype") %>%
  mutate(
    a.median.wt = filter(cml_data_avg, genotype == "WT")$a.median,
    hue.rescaled = hue.scaled * (a.median / a.median.wt)
  )

head(cml_data)
```

```{r boxplot data, fig.showtext = TRUE, out.width = '100%', message = FALSE}

cml_data_length <- cml_data %>%
  group_by(genotype, replicate, technical, ROI) %>%
  summarise(length = max(distance))

aov1 <- aov(data = cml_data_length, length ~ genotype)
length_letters <- HSD.test(aov1, "genotype", alpha = 0.05)
length_letters$groups[["genotype"]] <- rownames(length_letters$groups)
length_letters$groups[["length"]] <- 10
length_letters <- length_letters[["groups"]]

ggplot(
  data = cml_data_length,
  aes(
    x = genotype,
    y = length
  )
) +
  geom_jitter(
    width = 0.2,
    shape = 19,
    size = 2,
    stroke = 0,
    alpha = 0.25
  ) +
  geom_boxplot(
    fill = rgb(1, 1, 1, 0.5),
    outlier.alpha = 0
  ) +
  geom_text(
    data = length_letters,
    aes(label = groups),
    family = "Helvetica",
    size = 4.5
  ) +
  scale_x_discrete(
    labels = c(
      "WT",
      expression(italic("4cl1")),
      expression(italic("4cl2")),
      expression(paste(italic("4cl1"), "x", italic("4cl2"))),
      expression(italic("ccoaomt1")),
      expression(italic("fah1")),
      expression(italic("omt1")),
      expression(italic("ccr1")),
      expression(italic("cad4")),
      expression(italic("cad5")),
      expression(paste(italic("cad4"), "x", italic("cad5")))
    )
  ) +
  labs(y = "Cell wall thickness") +
  theme_leo()
```

```{r boxplots 2, fig.showtext = TRUE, out.width = '100%', message = FALSE}

cml_data_box <- cml_data %>%
  group_by(genotype, replicate, technical, ROI) %>%
  mutate(
    length = n(),
    position = ifelse(distance > (length(distance) / 2 - 2) & distance < (length(distance) / 2 + 2), "CML",
      ifelse(distance > (length(distance) / 2 - 5) & distance < (length(distance) / 2 - 1), "S1",
        ifelse(distance > (length(distance) / 2 + 1) & distance < (length(distance) / 2 + 5), "S1",
          ifelse(distance.scaled > 0.1 & distance.scaled < 0.35, "S2",
            ifelse(distance.scaled > 0.65 & distance.scaled < 0.9, "S2",
              ifelse(distance.scaled > 0.9 & distance.scaled < 0.98, "S3",
                ifelse(distance.scaled > 0.02 & distance.scaled < 0.1, "S3",
                  NA
                )
              )
            )
          )
        )
      )
    )
  ) %>%
  drop_na() %>%
  mutate(position = ordered(position, levels = c("CML", "S1", "S2", "S3")))

box_letters <- cml_data_box %>%
  group_by(position) %>%
  do(data.frame(tukey(.)))

if_box <- ggplot(
  data = cml_data_box,
  aes(
    x = genotype,
    y = hue
  )
) +
  geom_rect(
    data = tibble(position = c("CML", "S1", "S2", "S3")),
    aes(x = NULL, y = NULL, fill = position),
    xmin = -Inf,
    xmax = Inf,
    ymin = -Inf,
    ymax = Inf,
    alpha = 0.5
  ) +
  scale_fill_brewer(palette = "YlGnBu") +
  geom_quasirandom(
    width = 0.2,
    shape = 19,
    size = 0.5,
    stroke = 0,
    alpha = 0.25,
    # aes(colour = replicate)
  ) +
  geom_boxplot(
    fill = rgb(1, 1, 1, 0.75),
    outlier.alpha = 0,
    size = 0.2,
    fatten = 1
  ) +
  # geom_violin(
  #   fill = rgb(1, 1, 1, 0.5),
  #   draw_quantiles = 0.5
  # ) +
  geom_text(
    data = box_letters,
    aes(label = groups),
    family = "Helvetica",
    size = ggtext_size,
    label.size = 0,
    fill = rgb(1, 1, 1, 0.5),
    angle = 90,
    vjust = 0.5,
    hjust = 1
  ) +
  labs(y = "Hue") +
  scale_x_discrete(
    labels = c(
      "WT",
      expression(italic("4cl1")),
      expression(italic("4cl2")),
      expression(paste(italic("4cl1"), "x", italic("4cl2"))),
      expression(italic("ccoaomt1")),
      expression(italic("fah1")),
      expression(italic("omt1")),
      expression(italic("ccr1")),
      expression(italic("cad4")),
      expression(italic("cad5")),
      expression(paste(italic("cad4"), "x", italic("cad5")))
    )
  ) +
  scale_y_continuous(expand = expand_scale(mult = c(0.2, 0.05))) +
  theme_leo() +
  theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    axis.title.x = element_blank()
  ) +
  facet_wrap(~position, nrow = 1)

pdf("hue_box.pdf", height = 4, width = 10)
if_box
dev.off()
```

## Circular hue plot
```{r circ plot 3, fig.showtext = TRUE, out.width = '100%', message = FALSE}

circ_plot <- ggplot(cml_data_box %>% filter(genotype == "WT")) +
  geom_vline(xintercept = 310, size = 0.2) +
  annotate("text", x = 310, y = 0.15, label = "310 ",
           family = "Helvetica",
           hjust = 1,
           size = ggtext_size) +
  annotate("text", x = 330, y = 0.15, label = " 330",
           family = "Helvetica",
           hjust = 0,
           size = ggtext_size) +
  scale_fill_brewer(palette = "YlGnBu") +
  geom_vline(xintercept = 330, size = 0.2) +
  geom_density(aes(x = hue, fill = position),
               # colour = NA,
               size = 0.2,
               alpha = 0.5) +
  # coord_polar() +
  theme_leo() +
  labs(x = "Hue",
       y = "") +
  theme(legend.position = c(0.07, 0.79)) +
  guides(fill = guide_legend(title = "Layer"))

pdf("Blaschek2019_supp_cml_hue.pdf", width = twocol, height = onehalfcol)
plot_grid(
  circ_plot,
  if_box,
  nrow = 2,
  labels = c("A", "B"),
  label_size = 10,
  label_fontfamily = "Helvetica"
)
dev.off()

```