---
title: "C4H field trials"
author: "Leonard Blaschek"
date: "11/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(showtext)
# library(qrencoder)
library(cowplot)
library(grid)
library(gridExtra)
library(tidyverse)
library(broom)
library(ggrepel)
library(ggridges)
library(cowplot)
library(jsonlite)
library(slider)
library(lubridate)
library(baseline)

#### import Helvetica ####
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 6,
                      base_family = "Helvetica") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      axis.ticks = element_line(
        size = 0.125,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        size = 6,
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        size = 6,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_text(
        colour = "black",
        size = 6
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      axis.line = element_line(size = 0.2),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 6),
      legend.key.height = unit(4, "mm"),
      plot.title = element_text(
        size = 6,
        hjust = 0
      ),
      complete = TRUE
    )
}

pal_ostwald_disc <- c(
  "#275d95",
  "#e8c245",
  "#d25952"
)

pal_flame <- c(
  "#1F265D",
  # "#203F8F",
  "#404678",
  "#897B88",
  "#E7BBA2",
  "#FFEDC3",
  "#FEFEFE"
)

ggtext_size <- 6 / (14 / 5)
cm_size <- function(x) x / 2.54
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54
```

## Load data

```{r}
data1 <- read_csv("/home/leonard/Dropbox/2020_P_manuscript/P_data_1.csv") %>%
  pivot_longer(cols = -sample, names_to = "ID", values_to = "value") %>%
  separate(sample, into = c("genotype", "plant")) %>%
  separate(ID, into = c("variable", "date"), sep = " ") %>%
  mutate(instance = "1")

data2 <- read_csv("/home/leonard/Dropbox/2020_P_manuscript/P_data_2.csv") %>%
  pivot_longer(cols = -sample, names_to = "ID", values_to = "value") %>%
  separate(sample, into = c("genotype", "plant")) %>%
  separate(ID, into = c("variable", "date"), sep = " ") %>%
  mutate(instance = "2")

data <- data1 %>%
  bind_rows(data2) %>%
  mutate(date = as_date(parse_date_time(date, "ym")))
```

## View growth kinetics

```{r}
growth <- ggplot(data %>% filter(variable == "height")) +
  geom_line(aes(x = date, y = value, colour = genotype, group = interaction(genotype, plant)),
    alpha = 0.1
  ) +
  geom_smooth(aes(x = date, y = value, colour = genotype),
    method = "loess",
    span = 0.5
  ) +
  theme_leo() +
  theme(legend.position = "bottom") +
  facet_wrap(~instance, nrow = 2)

pdf("growth.pdf", height = onecol, width = onecol)
growth
dev.off()
```

## Split plant data into growth periods

```{r}
year_height <- data %>%
  mutate(
    year = isoyear(date),
    month = month(date)
  ) %>%
  group_by(instance, year, variable, genotype, plant) %>%
  mutate(
    "season" = case_when(
    date == max(date) ~ "endofyear",
    TRUE ~ "midyear")
    ) %>%
  filter(season == "endofyear" & variable == "height" & month > 9) %>%
  group_by(instance, genotype, plant) %>%
  mutate(age = year - min(year)) %>%
  arrange(date, .by_group = TRUE) %>%
  mutate(height_growth = value - lag(value, default = first(value))) %>%
  filter(year != min(year)) %>%
  ungroup() %>%
  select(genotype, plant, instance, year, age, height_growth)

year_width <- data %>%
  mutate(
    year = isoyear(date),
    month = month(date)
  ) %>%
  group_by(instance, year, variable, genotype, plant) %>%
  mutate("season" = case_when(
    date == max(date) ~ "endofyear",
    TRUE ~ "midyear"
  )) %>%
  filter(season == "endofyear" & variable == "width" & month > 9) %>%
  group_by(instance, genotype, plant) %>%
  arrange(date, .by_group = TRUE) %>%
  mutate(width_growth = value - lag(value, default = first(value))) %>%
  filter(year != min(year)) %>%
  ungroup() %>%
  select(genotype, plant, instance, year, width_growth)

year_injuries <- data %>%
  mutate(
    year = isoyear(date),
    month = month(date)
  ) %>%
  group_by(instance, year, variable, genotype, plant) %>%
  filter(variable == "injuries") %>%
  group_by(instance, genotype, plant, year) %>%
  summarise(injuries = max(value)) %>%
  filter(year != min(year)) %>%
  ungroup() %>%
  select(genotype, plant, instance, year, injuries)

year_survival <- data %>%
  mutate(
    year = isoyear(date),
    month = month(date)
  ) %>%
  group_by(instance, year, variable, genotype, plant) %>%
  filter(variable == "survival") %>%
  group_by(instance, genotype, plant, year) %>%
  summarise(survival = min(value)) %>%
  filter(survival == 0) %>%
  ungroup() %>%
  select(genotype, plant, instance, year, survival)

year_data <- year_height %>%
  full_join(year_width, by = c("genotype", "plant", "instance", "year")) %>%
  full_join(year_injuries, by = c("genotype", "plant", "instance", "year")) %>%
  anti_join(year_survival, by = c("genotype", "plant", "instance", "year")) %>%
  ungroup() %>%
  mutate(
    line = genotype,
    genotype = case_when(
      genotype == "WT" ~ "WT",
      TRUE ~ "<i>C4H</i>-RNAi"
    )
  )
```

## View yearly growth by genotype

```{r}
year_growth <- ggplot(
  year_data,
  aes(x = genotype, y = height_growth)
) +
  ggbeeswarm::geom_quasirandom(
    aes(fill = age),
    shape = 21,
    stroke = 0.2,
    size = 1,
    alpha = 0.5,
    width = 0.4
  ) +
  geom_violin(
    # aes(group = interaction(instance,genotype)),
    draw_quantiles = 0.5,
    colour = "black",
    alpha = 0.5,
    size = 0.2,
    width = 0.4
  ) +
  scale_fill_gradientn(colours = pal_flame) +
  labs(y = "Yearly growth increment [mm]") +
  theme_leo() +
  theme(legend.position = "bottom",
        legend.key.height = unit(1, "mm"),
        axis.text.x = ggtext::element_markdown(),
        axis.title.x = element_blank()) +
  facet_wrap(~instance)

pdf("year_growth.pdf", height = onecol * 0.5, width = onecol * 0.5)
year_growth
dev.off()
```

## Load environment data

```{r}
envir <- read_csv("/home/leonard/Dropbox/2020_P_manuscript/env_data.csv") %>%
  mutate(
    date = as_date(parse_date_time(date, "ym")),
    year = isoyear(date),
    month = month(date)
  )

year_envir <- envir %>%
  group_by(year) %>%
  summarise(
    lowest_temp = min(low_temp),
    highest_temp = max(high_temp),
    average_high_temp = mean(high_temp),
    average_low_temp = mean(low_temp),
    average_temp = mean(mean_temp),
    lowest_humidity = min(low_humidity),
    heighest_humidity = max(high_humidity),
    average_high_humidity = mean(high_humidity),
    average_low_humidity = mean(low_humidity),
    average_humidity = mean(mean_humidity),
    average_precipitation = mean(mean_precip),
    lowest_precipitation = min(total_precip),
    highest_wind = max(wind),
    average_wind = mean(wind),
    highest_light = max(irradiation),
    average_light = mean(irradiation)
  )

cumul_temp <- read_csv("/home/leonard/Dropbox/2020_P_manuscript/cumul_temp.csv") %>%
  mutate(
    date = as_date(parse_date_time(date, "ym")),
    year = isoyear(date),
    month = month(date)
  )

year_cumul_temp <- cumul_temp %>%
  group_by(year) %>%
  summarise(
    may_0deg = `cummul h above 0`[month == 5],
    may_5deg = `cummul h above 5`[month == 5],
    may_10deg = `cummul h above 10`[month == 5])
```

## Model optimisation

```{r}
optim_data <- year_data %>%
  left_join(year_envir, by = "year") %>%
  left_join(year_cumul_temp, by = "year") %>%
  mutate(quadratic_age = -(age - 3)^2) %>%
  ungroup() %>%
  filter(genotype == "WT") %>%
  # filter(genotype %in% c("1B", "3B")) %>%
  # filter(instance == 1) %>%
  # filter(instance == 2) %>%
  select(-c(genotype:year, line), -highest_light, -average_light) %>%
  drop_na(height_growth)

# Fit the full model 
full_model <- lm(height_growth ~., data = optim_data %>% select(-width_growth))
# Stepwise regression model
step_model <- MASS::stepAIC(full_model, direction = "both", 
                      trace = FALSE)
summary(step_model)

```

## Models

```{r}

#### partial regression plot for age ####
partial_model <- year_data %>%
  left_join(year_envir, by = "year") %>%
  left_join(year_cumul_temp, by = "year") %>%
  ungroup() %>%
  mutate(
    line = genotype,
    genotype = case_when(
      genotype == "WT" ~ "WT",
      TRUE ~ "<i>C4H</i>-RNAi"
    )
  ) %>%
  drop_na(height_growth) %>%
  nest(data = -c(genotype)) %>%
  mutate(
    growth_model = map(data, ~ lm(height_growth ~
    injuries +
      lowest_temp +
      highest_temp +
      average_high_temp +
      average_low_temp,
    data = .x
    )),
    age_model = map(data, ~ lm(age ~
    injuries +
      lowest_temp +
      highest_temp +
      average_high_temp +
      average_low_temp,
    data = .x
    )),
    growth_model_resid = map(growth_model, residuals),
    age_model_resid = map(age_model, residuals),
  ) %>%
  select(genotype, growth_model_resid, age_model_resid) %>%
  unnest(c(growth_model_resid, age_model_resid),
         names_repair = "unique")

pdf("age_residuals.pdf", height = onecol * 0.5, width = onecol * 0.5)
ggplot(partial_model,
       aes(
         x = age_model_resid,
         y = growth_model_resid
         )
       ) +
  geom_point(shape = 16, alpha = 0.5, size = 0.5) +
  geom_smooth(span = 1.5, size = 0.1) +
  theme_leo() +
  theme(strip.text = ggtext::element_textbox_simple()) +
  facet_wrap(~ genotype)
dev.off()


simple_model <- year_data %>%
  left_join(year_envir, by = "year") %>%
  left_join(year_cumul_temp, by = "year") %>%
  ungroup() %>%
  mutate(
    line = genotype,
    genotype = case_when(
      genotype == "WT" ~ "WT",
      TRUE ~ "<i>C4H</i>-RNAi"
    )
  ) %>%
  drop_na(height_growth) %>%
  nest(data = -c(genotype, instance)) %>%
  mutate(
    simple_model = map(data, ~ lm(height_growth ~
    injuries +
      age +
      lowest_temp +
      highest_temp +
      average_high_temp +
      average_low_temp,
    data = .x
    )),
    simple_pred = map(simple_model, predict),
    simple_glance = map(simple_model, glance),
    simple_tidy = map(simple_model, tidy)
  ) %>%
  unnest(c(simple_glance, simple_tidy),
         names_repair = "unique")

model_data <- year_data %>%
  left_join(year_envir, by = "year") %>%
  left_join(year_cumul_temp, by = "year") %>%
  ungroup() %>%
  mutate(
    line = genotype,
    genotype = case_when(
      genotype == "WT" ~ "WT",
      TRUE ~ "<i>C4H</i>-RNAi"
    )
  ) %>%
  drop_na(height_growth) %>%
  group_by(genotype, instance) %>%
  nest(data = -c(genotype)) %>%
  mutate(
    simple_model = map(data, ~ lm(height_growth ~
    injuries +
      age +
      lowest_temp +
      highest_temp +
      average_high_temp +
      average_low_temp,
    data = .x
    )),
    simple_pred = map(simple_model, predict),
    simple_glance = map(simple_model, glance),
    mixed_model = map(data, ~ lme4::lmer(height_growth ~
    injuries +
      age +
      lowest_temp +
      highest_temp +
      average_high_temp +
      average_low_temp +
      (1 | instance),
    data = .x
    )),
    mixed_r2 = map(mixed_model, MuMIn::r.squaredGLMM),
    mixed_r2 = map(mixed_r2, 2),
    mixed_r2 = as.numeric(mixed_r2),
    mixed_pred = map(mixed_model, predict),
    mixed_tidy = map(mixed_model, broom.mixed::glance),
  )

model_pred <- model_data %>%
  unnest(c(data, 
         simple_pred,
         mixed_pred
         ))

pdf("simple_model.pdf", height = onecol * 0.5, width = onecol * 0.5)
ggplot(model_pred,
       aes(x = mixed_pred, y = height_growth)) +
  geom_abline(size = 0.2,
              linetype = 2) +
  geom_point(shape = 16, alpha = 0.5, size = 0.5) +
  geom_smooth(method = "lm", size = 0.5) +
  # geom_line(aes(x = simple_pred, y = simple_pred)) +
  ggtext::geom_richtext(
    data = model_pred %>% select(genotype, instance, mixed_r2) %>% filter(instance == 1) %>% unique(),
    size = ggtext_size,
    # vjust = 0,
    hjust = 0,
    # colour = "black",
    label.colour = NA,
    family = "Helvetica",
    fill = NA,
    x = -80,
    y = 180,
    aes(label =
          paste0("R<sup>2</sup><sub>c</sub> = ",
                 format(round(mixed_r2, 2), nsmall = 2)
                 # ", <i>P</i> = ",
                 # format(p.value, scientific = TRUE, digits = 2)
                 ),
        # fontface = face
        )
  ) +
  facet_grid(instance ~ genotype) +
  scale_x_continuous(breaks = c(0, 100, 200)) +
  scale_y_continuous(breaks = c(0, 100, 200)) +
  coord_fixed(xlim = c(-50, 200),
              ylim = c(-50, 200)) +
  theme_leo() +
  theme(strip.text = ggtext::element_textbox_simple(),
        aspect.ratio = 1)
dev.off()
```

