---
title: "Poplar irx"
author: "Leonard Blaschek"
date: "09/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(showtext)
library(tidyverse)
library(ggthemes)
library(nlme)
library(piecewiseSEM)
library(cowplot)
library(ggridges)
library(ggbeeswarm)
library(tukeygrps)

font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica     [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 16,
                      base_family = "Helvetica") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      axis.ticks = element_line(
        size = 0.25,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_text(
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "bottom",
      legend.title = element_blank(),
      legend.text = element_text(size = rel(0.8)),
      legend.key.height = unit(4, "mm"),
      legend.key.width = unit(30, "mm"),
      # plot.margin = unit(c(0, 0, 0, 0), "cm"),

      complete = TRUE
    )
}
```

```{r, fig.showtext = TRUE, out.width = '100%', message = FALSE, eval = TRUE}

pop_irx <- read_csv("/home/leonard/Documents/Uni/PhD/IRX/Poplar/poplar_irx.csv")

#### create reference at the heigth of the cambium for distance calculation ####
pop_irx_ref <- pop_irx %>%
  filter(object == "ref") %>%
  select(c(
    "genotype",
    "replicate",
    "technical",
    "X",
    "Y",
    "Length"
  ))
pop_irx_ref$ref.y1 <- pop_irx_ref$Y
pop_irx_ref$ref.y2 <- pop_irx_ref$Y
pop_irx_ref$ref.x1 <- pop_irx_ref$X - (pop_irx_ref$Length / 2)
pop_irx_ref$ref.x2 <- pop_irx_ref$X + (pop_irx_ref$Length / 2)

#### merge reference into data frame ####
pop_irx <- pop_irx %>%
  filter(object != "ref") %>%
  full_join(select(pop_irx_ref, -X, -Y, -Length),
    by = c("genotype", "replicate", "technical")
  )

#### calculate difference of the centre of each vessel to the cambium ####
pop_irx$Distance <-
  apply(
    pop_irx[, c("X", "Y", "ref.x1", "ref.x2", "ref.y1", "ref.y2")],
    1,
    function(x) {
      a <- c(x[1], x[2])
      b <- c(x[3], x[5])
      c <- c(x[4], x[6])
      v1 <- b - c
      v2 <- a - b
      m <- cbind(v1, v2)
      d <- abs(det(m)) / sqrt(sum(v1 * v1))
      d
    }
  )

pop_irx <- pop_irx %>%
  mutate(bin = cut(
    Distance,
    breaks = c(-Inf, 50, 100, Inf),
    labels = c("I", "II", "III")
  ))

summary(lm(Circ. ~ n_v +
  n_f +
  Distance +
  Perim. +
  Mean,
data = pop_irx
))

model <- lm(Circ. ~ n_v +
  n_f +
  Distance +
  Perim. +
  Mean,
data = pop_irx
)

summary(model)
reghelper::beta(model)

cor.test(pop_irx$Circ., pop_irx$n_v)

ggplot(pop_irx, aes(x = n_v, y = Circ.)) +
  geom_point(aes(fill = genotype),
    shape = 21,
    size = 2,
    alpha = 0.75,
    stroke = 0.2
  ) +
  scale_fill_few() +
  theme_leo() +
  geom_smooth(
    method = "lm",
    span = 1,
    colour = "black",
    linetype = 2
  ) +
  facet_wrap(~genotype, ncol = 3)
```

```{r, fig.showtext = TRUE, out.width = '100%', message = FALSE, eval = TRUE}

pop_irx <- pop_irx %>%
  mutate(convexity = Area / ConvexArea)

left <- ggplot(data = pop_irx, aes(x = genotype, y = convexity)) +
  geom_jitter() +
  geom_boxplot()

right <- ggplot(data = pop_irx, aes(x = genotype, y = Circ.)) +
  geom_jitter() +
  geom_boxplot()

plot_grid(left, right, ncol = 2)

ggplot(pop_irx, aes(Circ., convexity)) +
  geom_point(
    aes(fill = genotype),
    shape = 21,
    alpha = 0.9,
    size = 2,
    stroke = 0.25
  ) +
  geom_smooth(
    span = 2,
    colour = "red",
    linetype = 2
  ) +
  scale_fill_viridis_d() +
  theme_leo()

ggplot(pop_irx, aes(x = n_v, y = convexity)) +
  geom_point(aes(fill = genotype),
    shape = 21,
    size = 2,
    alpha = 0.75,
    stroke = 0.2
  ) +
  scale_fill_few() +
  theme_leo() +
  geom_smooth(
    method = "lm",
    span = 1,
    colour = "black",
    linetype = 2
  ) +
  facet_wrap(~genotype, ncol = 3)

```


```{r}
find_interactions <- function(x) {
  pop_irx <- filter(pop_irx, type == x) %>%
  select(
    convexity,
    Perim.,
    Mean,
    # n_f,
    # n_p,
    n_v,
    Distance
  ) %>%
  drop_na()
  
  model.null <- lm(convexity ~ 1,
  data = pop_irx
)
model.full <- lm(convexity ~ (.)^2,
  data = pop_irx
)

best_model <- step(model.null,
  scope = list(upper = model.full),
  direction = "both",
  data = pop_irx
)

print(tidy(best_model) %>%
  select(term) %>%
  filter(str_detect(term, fixed(":"))))

best_model
}

#### primary vessels ####
best_model <- find_interactions("P")
summary(best_model)
broom::glance(best_model)

best_model <- find_interactions("S")
summary(best_model)
broom::glance(best_model)
```


```{r}

pop_irx <- as.data.frame(pop_irx)
poplar_psem <- psem(
    lm(Circ. ~
    n_v +
      Distance +
      # n_p +
      convexity,
    data = filter(pop_irx, type == "P")
    ),
    lm(convexity ~
    n_v +
      # n_p +
      Mean +
      Distance +
      Perim.,
    data = filter(pop_irx, type == "P")
    ),
    data = filter(pop_irx, type == "P")
  )

summary(poplar_psem)
plot(poplar_psem)

poplar_psem <- psem(
    lm(Circ. ~
    n_v +
      Distance +
      # n_p +
      convexity,
    data = filter(pop_irx, type == "S")
    ),
    lm(convexity ~
    n_v +
      # n_p +
      Mean +
      Distance +
      Perim.,
    data = filter(pop_irx, type == "S")
    ),
    data = filter(pop_irx, type == "S")
  )

summary(poplar_psem)
plot(poplar_psem)
```

```{r}
pdf("irx_neighbours_pop.pdf", width = 7, height = 5)
  ggplot(data = select(pop_irx, genotype, type, n_f, n_v, n_p, n_r) %>% 
           gather(key = "adjacency", value = "proportion",
                   n_f, n_v, n_p, n_r) %>%
           group_by(type, adjacency) %>%
           summarise(proportion.mean = mean(proportion, na.rm = TRUE),
                     proportion.sd = sd(proportion, na.rm = TRUE),
                     proportion.n = n()),
         aes(x = type, y = proportion.mean)) +
  geom_bar(
    aes(fill = adjacency),
    stat = "identity",
    # width = 0.1,
    alpha = 1,
    size = 2
    # stroke = 0.25
  ) +
  scale_fill_few() +
  # scale_fill_distiller(palette = "RdBu", name = "Z-score by\nrow") +
  # scale_y_continuous(expand = expand_scale(mult = c(0.28,0.05))) +
  # scale_x_discrete(
  #   labels = c(
  #     "Col-0",
  #     expression(italic("4cl1")),
  #     expression(italic("4cl2")),
  #     expression(paste(italic("4cl1"), "x", italic("4cl2"))),
  #     expression(italic("ccoaomt1")),
  #     expression(italic("fah1")),
  #     expression(italic("omt1")),
  #     expression(italic("ccr1")),
  #     expression(italic("cad4")),
  #     expression(italic("cad5")),
  #     expression(paste(italic("cad4"), "x", italic("cad5")))
  #   )
  # ) +
  # geom_text(aes(x = genotype, y = 0, label = proportion.n)) +
  theme_leo() +
  theme(text = element_text(size =20),
        legend.position = "bottom",
        axis.title = element_blank()) 
  # facet_wrap(~ cell.type, nrow = 1) 
# coord_flip()
  
  ggplot(data = pop_irx) +
    geom_density_ridges(aes(x = n_v, y = type, fill = type), alpha = 0.5) +
    theme_leo() 
  dev.off()
```

```{r}

pop_irx %>%
  group_by(genotype, replicate, type) %>%
  count()

pop_irx_overview <- pop_irx %>%
  ungroup() %>%
  select(
    genotype,
    type,
    n_v,
    Area,
    Circ.,
    Distance,
    convexity) %>%
  pivot_longer(n_v:convexity, names_to = "variable", values_to = "value") %>%
  drop_na()

write_csv(pop_irx_overview %>%
            filter(genotype == "WT") %>%
  group_by(genotype, type, variable) %>%
  summarise(value = mean(value)),
  "WT_values.csv")


pop_letters <- letter_groups(pop_irx_overview, value, genotype, "tukey", type, variable, print_position = "above")

pop_overview <- ggplot(pop_irx_overview,
                       aes(x = genotype,
                           y = value)) +
  geom_quasirandom() +
  geom_boxplot(alpha = 0.75,
               outlier.alpha = 0) +
  facet_grid(variable ~ type, scales = "free_y") +
  theme_leo() +
  geom_label(data = pop_letters,
            aes(label = groups),
            label.size = 0,
            alpha = 0.5)

pop_letters <- letter_groups(pop_irx_overview, value, type, "tukey", variable, genotype, print_position = "above")

pop_overview2 <- ggplot(pop_irx_overview,
                       aes(x = type,
                           y = value)) +
  geom_quasirandom() +
  geom_boxplot(alpha = 0.75,
               outlier.alpha = 0) +
  facet_grid(variable ~ genotype, scales = "free_y") +
  theme_leo() +
  geom_label(data = pop_letters,
            aes(label = groups),
            label.size = 0,
            alpha = 0.5)

# pop_neighbourhood <- ggplot(pop_irx, aes(x = n_v, y = convexity)) +
#   geom_point(aes(fill = genotype),
#     shape = 21,
#     size = 2,
#     alpha = 0.75,
#     stroke = 0.2
#   ) +
#   scale_fill_few() +
#   scale_y_continuous(limits = c(0.7,1)) +
#   labs(x = "Fraction of perimeter adjacent to other vessels") +
#   theme_leo() +
#   geom_smooth(
#     method = "loess",
#     span = 1,
#     colour = "black",
#     linetype = 2
#   ) +
#   facet_wrap(~ bin, ncol = 1)
# 
# pop_distance <- ggplot(pop_irx, aes(x = Distance, y = convexity)) +
#   geom_point(aes(fill = genotype),
#     shape = 21,
#     size = 2,
#     alpha = 0.75,
#     stroke = 0.2
#   ) +
#   scale_fill_few() +
#   scale_y_continuous(limits = c(0.7,1)) +
#   labs(x = "Distance from the cambium [µm]") +
#   theme_leo() +
#   geom_smooth(
#     method = "loess",
#     span = 1,
#     colour = "black",
#     linetype = 2
#   ) +
#   facet_wrap(~ bin, ncol = 1)

pdf("pop_overview.pdf")
pop_overview
pop_overview2
# pop_neighbourhood
# pop_distance
dev.off()
```

